version: '3.8'

services:
  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html/
    depends_on:
      - db

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "YourStrong@Passw0rd"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sqlserverdata:/var/opt/mssql
      
  initdb:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "YourStrong@Passw0rd"
      ACCEPT_EULA: "Y"
    volumes:
      - ./script.sql:/script.sql
    command: /bin/bash -c 'sleep 30s; /opt/mssql-tools18/bin/sqlcmd -S db -U sa -P YourStrong@Passw0rd -d master -i /script.sql -No -C'
    depends_on:
      - db

volumes:
  sqlserverdata:
